### ISSUE TITLE
EntryPointNotFoundException on Windows XP

### ISSUE THREAD

**Issue by kegfire** [Syroot/KnownFolders#2]
Hello,
When I try to run the code
`var folder = new KnownFolder(KnownFolderType.Downloads).Path;`
I get an error
```
System.EntryPointNotFoundException: Unable to find an entry point named 'SHGetKn
ownFolderPath' in DLL 'Shell32.dll'.
   at Syroot.Windows.IO.KnownFolder.SHGetKnownFolderPath(Guid rfid, UInt32 dwFla
gs, IntPtr hToken, IntPtr& ppszPath)
   at Syroot.Windows.IO.KnownFolder.GetPath(KnownFolderFlags flags)
   at Syroot.Windows.IO.KnownFolder.get_Path()
   at Less05_task05.Program.Main(String[] args)
```

Environment:
Windows XP sp3
Net Framework 4.0

**Comment by RayKoopa** [comment]
Windows XP is not supported.
